### ISSUE TITLE
If we make this public, we could link to this repo from Tammer's blog post

### ISSUE THREAD

**Issue by cjcjameson** [pivotal/usb-login-scripts#4]
Doesn't have to happen now, but just a thought

**Comment by davidje13** [comment]
I've been given the go-ahead to make this public under an Apache 2 license. All files have to have a license blurb now (I've updated the existing files).

**Comment by cjcjameson** [comment]
https://github.com/tsaleh/tammersaleh.com/pull/86

**Comment by davidje13** [comment]
Looks like your PR was accepted, so I'm closing this as complete.
